language: ruby
sudo: false
cache: bundler

rvm:
  - 2.0
  - 2.1
  - 2.2

env:
  - rails=3.2.0
  - rails=4.1.0
  - rails=4.2.0

gemfile:
  - gemfiles/Gemfile.sequel.rb

matrix:
  exclude:
    - env: rails=3.2.0
      rvm: 2.2
